Project1/config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  get 'show' => 'bookings#show'
  get 'search_room' =>'bookings#search_room'
  post 'search_room', to: 'bookings#search'
  get 'release_room' =>'bookings#release_room'
  post 'release_room', to: 'bookings#release'
  post 'index',to:'bookings#save_room'
  post'/cancel', to: 'bookings#cancel'

  # get 'sessions/new'
  root  'sessions#new'

  resources :rooms
  get 'view_room_history/:id', to: 'rooms#view_room_history', as: "view_room_history"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    get :show_admins
    get :add_admin
  end

  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  delete   '/logout',   to: 'sessions#destroy'

  get     '/login',     to: 'sessions#new'
  get     '/show_admins', to: 'users#show_admins'
  get   '/add_admin',    to: 'users#add_admin'
  # patch   '/add_admin',    to: 'users#add_admin'
  # post     '/add_admin',    to: 'users#add_admin'
  get   '/search_admin',    to: 'users#search_admin'
  patch   '/search_admin',    to: 'users#search_admin'
  post     '/search_admin',    to: 'users#search_admin'
  post     '/make_admin',        to: 'users#make_admin'
  post     '/remove_admin',        to: 'users#remove_admin'
  get      '/admin_manage_room',    to: 'users#admin_manage_room'
  get      '/admin_manage_user',    to: 'users#admin_manage_user'
  get       '/all_user',            to: 'users#all_user'
  post      '/remove_user',         to: 'users#remove_user'

  get       '/search_room',          to: 'bookings#search_room'
  get       '/user_manage_room',      to: 'users#user_manage_room'
  get       '/my_booking_history',            to: 'users#my_booking_history'

  post     '/room_availability_by_date',     to: 'bookings#room_availability_by_date'

  get       '/send_mail',               to: 'bookings#send_mail'
  post      '/dispatch_mail',           to: 'bookings#dispatch_mail'

  post       '/user_booking_history',            to: 'users#user_booking_history'
end

Project1/app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = self.email.downcase}
  has_many :booking
  validates :name,
            presence: true,
            length: {maximum: 80},
            format: {with: /\A[a-zA-Z ]+\z/}

  validates :email, presence: true,
            length: {maximum: 100},
            format: {with: /\A[\w\-.]+[@][a-z\d\-]+[\.[a-z\d\-]+]*[\.][a-z]+\z/i},
            uniqueness: {case_sensitive: false}

  validates :password, presence: true,
            length: {minimum: 6},
            format: {with: /[\d\W]/}


  has_secure_password

  def self.get_admins
    @all_users = User.where(Admin: true).all
  end


end

Project1/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :allowed_user, only: [:show, :edit, :update, :show_admins, :add_admin, :search_admin,
                                      :make_admin, :admin_manage_room, :remove_admin, :admin_manage_user,
                                      :all_user, :remove_user]


  def show
    @user = User.find(session[:user_id])
  end

  def new
    @user = User.new
  end


  def create
    @user = User.new(allowed_params)
    @user.Admin = false
    if @user.save
      flash[:success] = ("Registration successful " + @user.name)
      if user_logged_in? and User.find(session[:user_id]).Admin
        redirect_to admin_manage_user_path
      else
        logging_in(@user.id)
        redirect_to user_url(@user)
      end

    else
      render 'new'
    end
  end

  def edit
    @user = User.find(session[:user_id])

  end

  def update
    @user = User.find(session[:user_id])
    if @user.update_attributes(allowed_params)
      flash[:success] = "Update successful"
      redirect_to user_url(@user)
    else
      render 'edit'
    end
  end

  def show_admins
    if user_logged_in?
      @all_admins = User.get_admins
    else
      redirect_to login_path
    end
  end

  def add_admin
    @admin_user = User.new
  end

  def search_admin
    # debugger
    @user_search = User.where(return_email).all
    if @user_search[0]!=nil
      flash.now[:success] = "#{@user_search[0].email} matched"
      @search_result = @user_search[0]
      @admin_user = @user_search[0]
    else
      flash.now[:danger] = "Email not found"
      @admin_user = User.new
    end
    render 'add_admin'
  end

  def make_admin
    # debugger
    @user_for_admin = User.find_by(email: params[:email])
    if @user_for_admin.Admin
      flash.now[:danger] = "#{@user_for_admin.name} already an admin"
    else
      # @user_for_admin.Admin = true
      if @user_for_admin.update_attribute(:Admin, true)
        flash.now[:success] = "#{@user_for_admin.name} successfully added as admin"
      else
        flash.now[:danger] = "Cannot be added as admin. Please try again"
      end
    end
    @admin_user = User.new
    render  'add_admin'
  end

  def remove_admin
    @user_for_admin = User.find_by(email: params[:email])
    if @user_for_admin.update_attribute(:Admin, false)
        flash.now[:success] = "#{@user_for_admin.name} successfully removed as admin"
      else
        flash.now[:danger] = "#{@user_for_admin.name} cannot be removed as admin. Please try again"
    end
    @all_admins = User.get_admins
    render  'show_admins'
  end

  def admin_manage_room
    @user = User.find(session[:user_id])
  end

  def admin_manage_user
  end

  def user_manage_room
    @user = User.find(session[:user_id])
  end

  def user_booking_history
    @mail = params[:email]
    @my_booking = Booking.where(name: @mail).all
  end

  def my_booking_history
    @user = User.find(session[:user_id])
    @my_booking = Booking.where(name: @user.email).all
  end

  def all_user
    @all_users = User.where(Admin: false).all
  end

  def remove_user

    @user_for_deletion = User.find_by(email: params[:email])
    
    current_time=Time.new.strftime('%Y-%m-%d %H:%M:%S')
    @record=Booking.where("name= ? and starttime > ?",@user_for_deletion.name,current_time)
    @record.each do |booking|
    booking.destroy
    end
    if @user_for_deletion.destroy
      flash.now[:success] = "#{@user_for_deletion.name} successfully removed as user"
    else
      flash.now[:danger] = "#{@user_for_deletion.name} cannot be removed as user. Please try again"
    end
    @all_users = User.where(Admin: false).all
    redirect_to all_user_path
  end


  private

    def allowed_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def return_email
      params.require(:user).permit(:email)
    end



end

Project1/app/views/users/add_admin.html.erb
<h1>Add Admin</h1>
<body>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for @admin_user, url: search_admin_url do |field| %>
        <%= field.label :email %>
        <%= field.email_field :email %>
        <%= field.submit "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div></br>

<div class="row">
  <ul class="list-group">
    <h2><%= "Search Results"%> </h2>
    <% if @search_result!=nil%>
        <li class="list-group-item">
          <%= @search_result.name %>&nbsp&nbsp&nbsp&nbsp
          <%= @search_result.email %>&nbsp&nbsp&nbsp&nbsp
          <%= link_to "Make admin", make_admin_url(:email => @search_result.email) , method: "post" %>
        </li>
    <%end%>
  </ul>
</div>
</body>

Project1/app/views/users/admin_manage_room.html.erb
<body>
<h2>
  Manage Rooms
</h2>

<ul class="list-group">
      <li class="list-group-item"><%= link_to "Add room", new_room_url , method: "get" %></li>
      <li class="list-group-item"><%= link_to "View/Edit/Delete room", rooms_url, method: "get" %></li>
      <li class="list-group-item"><%= link_to "Book room", search_room_url , method: "get" %></li>
</ul>
</body>

Project1/app/views/users/admin_manage_user.html.erb
<body>
<h2>
  Manage Users
</h2>

<ul class="list-group">
  <li class="list-group-item"><%= link_to "All users", all_user_path , method: "get" %></li>
  <li class="list-group-item"><%= link_to "Reservation history", all_user_path, method: "get" %></li>
  <li class="list-group-item"><%= link_to "Add user", new_user_path , method: "get" %></li>
  <li class="list-group-item"><%= link_to "Remove user", all_user_path , method: "get" %></li>

</ul>
</body>

Project1/app/views/users/all_user.html.erb
<h1>Users</h1>
<body>
<ul class="list-group">
  <% @all_users.each do |each_user| %>
      <li class="list-group-item">
        <%= each_user.name %>&nbsp&nbsp&nbsp&nbsp
        <%= each_user.email %>&nbsp&nbsp&nbsp&nbsp
        <%= link_to "Reservation History", user_booking_history_url(:email => each_user.email) , method: "post" %>&nbsp&nbsp&nbsp&nbsp
        <%= link_to "Remove user", remove_user_url(:email => each_user.email) , method: "post", data: { confirm: 'Are you sure?' } %>
      </li>
  <% end %>
</ul>
</body>

<%= link_to 'Return to manage users', admin_manage_user_url %></table>

Project1/app/views/users/edit.html.erb
<h1>Update Profile</h1>
<body>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'shared/error_messages'%>

      <%= form_for(@user) do |field| %>
          <%= field.label :name %>
          <%= field.text_field :name %>

          <%= field.label :email %>
          <%= field.email_field :email %>

          <%= field.label :password %>
          <%= field.password_field :password %>

          <%= field.label :password_confirmation, "Password Confirmation" %>
          <%= field.password_field :password_confirmation %>

          <%= field.submit "Update", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</body>

Project1/app/views/users/my_booking_history.html.erb
<h1>My Booking history</h1>

<table class="details">
  <thead>
  <tr>
    <th>Room</th>
    <th>Username</th>
    <th>Bookday</th>
    <th>Date</th>
    <th>Starttime</th>
    <th>Endtime</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @my_booking.each do |booking| %>
      <tr>
        <td><%= booking.room_id %></td>
        <td><%= booking.name %></td>
        <td><%= booking.bookday %></td>
        <td><%= booking.date.strftime('%Y-%m-%d') %></td>
        <td><%= booking.starttime.strftime('%H:%M:%S') %></td>
        <td><%= booking.endtime.strftime('%H:%M:%S') %></td>
        <% if Date.parse(booking.date.strftime('%Y-%m-%d'))>=Date.parse(Time.new.strftime('%Y-%m-%d'))%>
            <td><%= link_to 'cancel', release_room_path(booking), method: :POST, data: { confirm: "Are you sure to cancel it?" }%></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back to Manage Rooms', user_manage_room_url %>

Project1/app/views/users/new.html.erb
<h1>Sign up</h1>
<body>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'shared/error_messages'%>

      <%= form_for(@user) do |field| %>
          <%= field.label :name %>
          <%= field.text_field :name %>

          <%= field.label :email %>
          <%= field.email_field :email %>

          <%= field.label :password %>
          <%= field.password_field :password %>

          <%= field.label :password_confirmation, "Password Confirmation" %>
          <%= field.password_field :password_confirmation %>

          <%= field.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</body>

Project1/app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <body>
  <h2>
    Welcome <%= @user.name %>
  </h2>

  <ul class="list-group">
    <li class="list-group-item"><%= link_to "Update profile", edit_user_url , method: "get" %></li>
    <% if @user.Admin%>
      <li class="list-group-item"><%= link_to "Add admin", add_admin_url, method: "get" %></li>
      <li class="list-group-item"><%= link_to "View admins", show_admins_url , method: "get" %></li>
      <li class="list-group-item"><%= link_to "Delete admin", show_admins_url , method: "get" %></li>
      <li class="list-group-item"><%= link_to "Manage rooms", admin_manage_room_url , method: "get" %></li>
      <li class="list-group-item"><%= link_to "Manage users", admin_manage_user_url , method: "get" %></li>
    <% else%>
        <li class="list-group-item"><%= link_to "Manage rooms", user_manage_room_url , method: "get" %></li>
  <%end%>
  </ul>
  </body>
</html>

Project1/app/views/users/show_admins.html.erb
<h1>Admins</h1>
<body>
<ul class="list-group">
   <% @all_admins.each do |each_user| %>
      <li class="list-group-item">
          <%= each_user.name %>&nbsp&nbsp&nbsp&nbsp
          <%= each_user.email %>&nbsp&nbsp&nbsp&nbsp
        <% if each_user.id != 1 && !match_session_id(each_user.id)%>
            <%= link_to "Remove as admin", remove_admin_url(:email => each_user.email) , method: "post", data: { confirm: 'Are you sure?' }%>
        <%end%>
      </li>
  <% end %>
</ul>
</body>

Project1/app/views/users/user_booking_history.html.erb
<h1>Booking history</h1>

<table class="details">
  <thead>
  <tr>
    <th>Room</th>
    <th>Username</th>
    <th>Bookday</th>
    <th>Date</th>
    <th>Starttime</th>
    <th>Endtime</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @my_booking.each do |booking| %>
      <tr>
        <td><%= booking.room_id %></td>
        <td><%= booking.name %></td>
        <td><%= booking.bookday %></td>
        <td><%= booking.date.strftime('%Y-%m-%d') %></td>
        <td><%= booking.starttime.strftime('%H:%M:%S') %></td>
        <td><%= booking.endtime.strftime('%H:%M:%S') %></td>
        <% if Date.parse(booking.date.strftime('%Y-%m-%d'))>=Date.parse(Time.new.strftime('%Y-%m-%d'))%>
            <td><%= link_to 'cancel', release_room_path(booking), method: :POST, data: { confirm: "Are you sure to cancel it?" }%></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', all_user_url %>

Project1/app/views/users/user_manage_room.html.erb
<body>
<h2>
  Manage Rooms
</h2>

<ul class="list-group">
  <li class="list-group-item"><%= link_to "View rooms", rooms_url, method: "get" %></li>
  <li class="list-group-item"><%= link_to "Book room", search_room_url , method: "get" %></li>
  <li class="list-group-item"><%= link_to "My Booking History", my_booking_history_url , method: "get" %></li>

</ul>
</body>