Project1/config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  get 'show' => 'bookings#show'
  get 'search_room' =>'bookings#search_room'
  post 'search_room', to: 'bookings#search'
  get 'release_room' =>'bookings#release_room'
  post 'release_room', to: 'bookings#release'
  post 'index',to:'bookings#save_room'
  post'/cancel', to: 'bookings#cancel'

  # get 'sessions/new'
  root  'sessions#new'

  resources :rooms
  get 'view_room_history/:id', to: 'rooms#view_room_history', as: "view_room_history"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    get :show_admins
    get :add_admin
  end

  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  delete   '/logout',   to: 'sessions#destroy'

  get     '/login',     to: 'sessions#new'
  get     '/show_admins', to: 'users#show_admins'
  get   '/add_admin',    to: 'users#add_admin'
  # patch   '/add_admin',    to: 'users#add_admin'
  # post     '/add_admin',    to: 'users#add_admin'
  get   '/search_admin',    to: 'users#search_admin'
  patch   '/search_admin',    to: 'users#search_admin'
  post     '/search_admin',    to: 'users#search_admin'
  post     '/make_admin',        to: 'users#make_admin'
  post     '/remove_admin',        to: 'users#remove_admin'
  get      '/admin_manage_room',    to: 'users#admin_manage_room'
  get      '/admin_manage_user',    to: 'users#admin_manage_user'
  get       '/all_user',            to: 'users#all_user'
  post      '/remove_user',         to: 'users#remove_user'

  get       '/search_room',          to: 'bookings#search_room'
  get       '/user_manage_room',      to: 'users#user_manage_room'
  get       '/my_booking_history',            to: 'users#my_booking_history'

  post     '/room_availability_by_date',     to: 'bookings#room_availability_by_date'

  get       '/send_mail',               to: 'bookings#send_mail'
  post      '/dispatch_mail',           to: 'bookings#dispatch_mail'

  post       '/user_booking_history',            to: 'users#user_booking_history'
end

Project1/app/models/booking.rb
class Booking < ApplicationRecord
  validate :endtime, :starttime,  on: :create
  # validates :room_id, presence: true
  def time_period
    errors.add("Bookings can be made for 2 hour slots") unless Integer(endtime)-Integer(startime)<=4

  end
end

Project1/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :allowed_user
  #before_action :set_booking, only: [:show, :edit, :update, :destroy]
  @@req_rooms=nil
  require'time'
  @@hello=nil
  @@bookinfomail=nil

  # @@curuser = User.find(session[:user_id])
  # GET /bookings
  # GET /bookings.json
  def index
    @newbooking=Booking.new
    @all_bookings = Booking.new
    if @@req_rooms
      @bookings=@@req_rooms

      room_ids = []
      @bookings.each do |i|
        room_ids.push(i.room_id)
      end
      @all_bookings = Booking.where(room_id: room_ids).all
      # debugger

      @booking_matrix = []
      cur_date = Time.now
      # temp = "%04d-%02d-%02d 00:00:00" %[cur_date.year, cur_date.month, cur_date.day]

      (1..7).each do |k|
        room_ids.each do |er|
          temp = "%04d-%02d-%02d 00:00:00" %[cur_date.year, cur_date.month, cur_date.day]
          temparr = @all_bookings.where(room_id: er, date: temp).all
          @booking_matrix.push(get_array(temparr))

        end
        cur_date = cur_date + (24*60*60)
      end

      # debugger
    else
      @bookings = Room.new
    end
    # @hours = ["00:00", "00:30" ]
    @hours = []
    (0..23).each do |i|
      ["00", "30"].each do |j|
        @hours.push("#{i}:#{j}")
        end
    end
    @roomids = Room.all.pluck(:room_id)
    @loginuser=User.find(session[:user_id])
    @users=User.all.pluck(:email)
    # #debugger
  end

  def get_array(all_bookings)
    timeslot=Array.new(48,0)
    all_bookings.each do |book|
      startindex=(book.starttime.hour)*2+(book.starttime.min)/30
      endindex=(book.endtime.hour)*2+(book.endtime.min)/30
      while startindex<endindex
        timeslot[startindex]=1
        startindex=startindex+1
      end
    end
    return timeslot
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  	user=User.find(session[:user_id]).email    
    @showing_booking=Booking.where("name =?",user)
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit

  end


######release room
  def release_room

    current_time=Time.new
    current_date=current_time.strftime('%Y-%m-%d')
    user=User.find(session[:user_id]).email
    #debugger
    @bookings=Booking.where("name = ? and endtime >= ?",user,current_time)
    ##debugger

  end


  def release
    current_time=Time.new
    current_date=current_time.strftime('%Y-%m-%d')
    current_timeout=current_time.strftime('%H:%M:%S')#the time of release
    @recordbookings = Booking.find(params[:format])
    #debugger
    #the time before starttime 
    if @recordbookings.starttime > current_time
    	@recordbookings.destroy
    #the release time
    else 
    	endtime=timeslot(current_time)
      @recordbookings.update(endtime: endtime)
    end
    #debugger
    if User.find(session[:user_id]).Admin
      redirect_to all_user_url
    else
      redirect_to my_booking_history_url
    end


  end

######search room by some keywords
  def search_room
    @rooms=Room.new
    

    # #debugger
  end

  def room_availability_by_date

    @req_date = booking_date
    temp = "%04d-%02d-%02d 00:00:00" %[@req_date["date(1i)"], @req_date["date(2i)"], @req_date["date(3i)"]]

    @bookings=@@req_rooms
    room_ids = []
    @bookings.each do |i|
      room_ids.push(i.room_id)
    end
    @all_bookings = Booking.where(room_id: room_ids, date: temp).all


  end


  def search
    @room = Room.new(room_params)
    @@req_rooms = Room.all
    # #debugger
    if @room.size!=""
      @@req_rooms = @@req_rooms.where(size: @room.size).all
    end
    if @room.building!=""
      @@req_rooms = @@req_rooms.where(building: @room.building).all
    end
    if @room.room_id != ""
      @@req_rooms = @@req_rooms.where(room_id: @room.room_id).all
    end
    redirect_to bookings_path
  end


  # POST /bookings
  # POST /bookings.json

  def create
    flag=0
    @@bookinfomail = Booking.new(booking_params)
    @booking = Booking.new(booking_params)
    @user=User.find(session[:user_id])
    if not @user.Admin
       # debugger
       @booking.name = User.find(session[:user_id]).email
       flag=1
    end
     #name is in fact the email of the person who books the room (By Lei Zhang)
     @booking.bookday=Time.new
    #<begin> edit by Lei Zhang
    starttime_string = booking_params[:starttime]
    if starttime_string.length == 4
        starttime_string = "0" + starttime_string
    end
    endtime_string = booking_params[:endtime]
    if endtime_string.length == 4
        endtime_string = "0" + endtime_string
    end
    
    @booking.endtime = Time.parse("%04d-%02d-%02d %s:00" %[booking_params["date(1i)"], booking_params["date(2i)"], booking_params["date(3i)"], endtime_string])
    @booking.starttime = Time.parse("%04d-%02d-%02d %s:00" %[booking_params["date(1i)"], booking_params["date(2i)"], booking_params["date(3i)"], starttime_string])
    #debugger
    #<end> edited by Lei Zhang
    #--------------
    @bookingrecord=Booking.where("room_id= ? and date = ?",booking_params[:room_id],@booking.date)
    @record=Booking.where("name=? and date = ?", @booking.name,@booking.date)
    #-------------
    #<begin> edited by Lei Zhang
    #debugger
    duration = @booking.endtime - @booking.starttime
    if ((duration/1800 > 4) || (duration<=0))
      flash[:danger] = "Cannot book for more that 2 hours or less than 0 hours"
      redirect_to bookings_path
    elsif not (timeconstrain(@bookingrecord,@booking))
      flash[:danger] = "The room is booked during that period. Try another room or another time"
      redirect_to bookings_path
    elsif (@booking.starttime <= Time.new) ||((Time.parse(@booking.date.strftime('%Y-%m-%d'))-Time.parse(Time.new.strftime('%Y-%m-%d'))).round/(3600*24)>7)
      flash[:danger] = "The time period is not correct"
      redirect_to bookings_path
    elsif (flag==1)&&( not (bookroom_constrain(@record,@booking.starttime,@booking.endtime)))
      flash[:danger] = "A library member can reserve only one room at a particular date and time"
      redirect_to bookings_path
    else
      # respond_to do |format|
      #    if @booking.save
      #     format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
      #     format.json { render :show, status: :created, location: @booking }
      #   else
      #     format.html { render :new }
      #     format.json { render json: @booking.errors, status: :unprocessable_entity }
      #    end
      # end
      if @booking.save
        #debugger
        flash[:success] = "Room successfully booked"
      # redirect_to bookings_path
      #   redirect_to bookings_path
        redirect_to send_mail_path
      else
        flash[:danger] = "Cannot book room now. Please try again later"
        redirect_to bookings_path
      end
    end
 end


  def send_mail

  end

  def dispatch_mail
    # debugger
    # UsermailerMailer.welcome_email(params[:email]).deliver_now
    UsermailerMailer.notification_email(@@bookinfomail, params[:email]).deliver_now
    redirect_to send_mail_path
  end


  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json

  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:room_id, :name, :string, :bookday, :date, :starttime, :endtime)
    end

    def booking_date
      params.require(:booking).permit(:date)
    end

    def room_params
      params.require(:room).permit(:size, :building,:room_id)
    end

    def timeconstrain(bookingrecord,booking )
        timeslot=Array.new(48,0)
        bookingrecord.each do |book|
        startindex=(book.starttime.hour)*2+(book.starttime.min)/30
        endindex=(book.endtime.hour)*2+(book.endtime.min)/30
        while startindex<endindex
          timeslot[startindex]=1
          startindex=startindex+1
        end
        end
        insertstart=(booking.starttime.hour)*2+(booking.starttime.min)/30
        insertend=(booking.endtime.hour)*2+(booking.endtime.min)/30
        while insertstart<insertend
              if timeslot[insertstart]!=0
                return false
              end
              insertstart=insertstart+1
        end#while
        return true
    end#function

    def timeslot(current_time)
        current_time+=60-current_time.sec
        if (current_time.min % 30) != 0
          current_time+=60*(30-current_time.min%30)
        end
        return current_time
    end

 

    def bookroom_constrain(record,starttime,endtime)
    	  timeslot=Array.new(48,0)
        record.each do |book|
        startindex=(book.starttime.hour)*2+(book.starttime.min)/30
        endindex=(book.endtime.hour)*2+(book.endtime.min)/30
        while startindex<endindex
          timeslot[startindex]=1
          startindex=startindex+1
        end
        end
        insertstart=(starttime.hour)*2+(starttime.min)/30
        insertend=(endtime.hour)*2+(endtime.min)/30
        while insertstart<insertend
              if timeslot[insertstart]!=0
                return false
              end
              insertstart=insertstart+1
        end#while
        return true
    end
end

Project1/app/helpers/bookings_helper.rb
module BookingsHelper
end

Project1/app/views/bookings/_form.html.erb
<%= form_for(booking) do |f| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_id %>
    <%= f.text_field :room_id %>
  </div>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :bookday %>
    <%= f.datetime_select :bookday %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="field">
    <%= f.label :starttime %>
    <%= f.text_field :starttime %>
  </div>

  <div class="field">
    <%= f.label :endtime %>
    <%= f.text_field :endtime %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Project1/app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

Project1/app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1> Room Information</h1>
<body>


  <!--<div class="row">-->
    <!--<div class="col-md-6 col-md-offset-3">-->

      <!--<%= form_for @newbooking, :url => room_availability_by_date_path do|f| %>-->
          <!--<%= f.label :Date %>-->
          <!--<%= f.date_select :date %>-->

          <!--<%= f.submit "Search", class: "btn btn-primary"%>-->

      <!--<%end%>-->
    <!--</div>-->
  <!--</div>-->

  <h2> Room availability </h2>


  <div class="row">
    <div class="col-md-3 col-md-offset-1">
        <table>
          <tr>
            <th>Date</th>
            <th>Room</th>
            <% (0..23).each do |i| %>
              <th colspan="2"><%=i%></th>
            <%end%>
          </tr>
          <% count = 0 %>
        <%(1..7).each do |k|%>
          <%@bookings.each do |booking| %>
              <tr>
                <th><%=Date.today + (k-1) %></th>
                <th><%= booking.room_id %></th>
                <% (1..48).each do |i| %>


                    <% if @booking_matrix[count][i-1]==0 %>
                        <th bgcolor="#A0A0A0"></th>
                    <% else %>
                        <th bgcolor="#FF0000"></th>
                    <%end%>


              <%end%>
                <%count = count + 1%>
              </tr>
            <% end %>
        <%end%>
      </table>
    </div>
  </div>


  <h2>Please fill the form to book a room</h2>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">

      <%= form_for @newbooking do|f| %>
                <%= f.label :room_id %>
                <%= f.select :room_id, @roomids %>
                <% if @loginuser.Admin%>
                <%= f.label :name %>
                <%= f.select :name, @users %>
                <% end %>
                <%= f.label :Date %>
                <%= f.date_select :date %>

                <%= f.label :"Start-Time" %>
                <%= f.select :starttime, @hours %>

                <%= f.label :"End-Time" %>
                <%= f.select :endtime, @hours %>

                <%= f.submit "Book", class: "btn btn-primary"%>

          <%end%>
        </div>
      </div>


</body>

<%= link_to 'Back to Search Rooms', search_room_url %>

Project1/app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

Project1/app/views/bookings/release_room.erb
<h1>release the room you book</h1>

<table>
  <thead>
  <tr>
    <th>Room</th>
    <th>Date</th>
    <th>Starttime</th>
    <th>Endtime</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.room_id %></td>
        <td><%= booking.date.strftime('%Y-%m-%d') %></td>
        <td><%= booking.starttime.strftime('%H:%M:%S') %></td>
        <td><%= booking.endtime.strftime('%H:%M:%S') %></td>
        <% if Date.parse(booking.date.strftime('%Y-%m-%d'))>=Date.parse(Time.new.strftime('%Y-%m-%d'))%>
            <td><%= link_to 'cancel', release_room_path(booking), method: :POST, data: { confirm: "Are you sure to cancel it?" }%></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

Project1/app/views/bookings/sample_email.text.erb
Sample mail sent using smtp.

Project1/app/views/bookings/search_room.erb
<h1>Search Room</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

      <%= form_for @rooms, url: search_room_path do |f| %>

          <%= f.label :size %>
          <%= f.select :size, [nil, 4, 6, 12] %>

          <%= f.label :building %>
          <%= f.select :building, [nil, "James B. Hunt", "D. H. Hill"] %>

          <%= f.label :room_id %>
          <%= f.text_field :room_id %>

          <%= f.submit "Search", class: "btn btn-primary" %>

  <% end %>
  </div>
</div>

Project1/app/views/bookings/send_mail.html.erb
<h1> Send email notification</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <form action="/dispatch_mail" method="post">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= label_tag(:email, "Email id") %>
      <%= text_field_tag(:email) %>
      <%= submit_tag "Send mail",  class: "btn btn-primary" %>
    </form>

  </div>
</div>

<% link_to 'Back to Manage Rooms', user_manage_room_url %>

Project1/app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<h1> the booking history </h1>

<table>
  <thead>
  <tr>
    <th>Room</th>
    <th>Username</th>
    <th>Bookday</th>
    <th>Date</th>
    <th>Starttime</th>
    <th>Endtime</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @showing_booking.each do |booking| %>
      <tr>
        <td><%= booking.room_id %></td>
        <td><%= booking.name %></td>
        <td><%= booking.bookday %></td>
        <td><%= booking.date.strftime('%Y-%m-%d') %></td>
        <td><%= booking.starttime.strftime('%H:%M:%S') %></td>
        <td><%= booking.endtime.strftime('%H:%M:%S') %></td>
      </tr>
  <% end %>
  </tbody>
</table>