Project1/config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  get 'show' => 'bookings#show'
  get 'search_room' =>'bookings#search_room'
  post 'search_room', to: 'bookings#search'
  get 'release_room' =>'bookings#release_room'
  post 'release_room', to: 'bookings#release'
  post 'index',to:'bookings#save_room'
  post'/cancel', to: 'bookings#cancel'

  # get 'sessions/new'
  root  'sessions#new'

  resources :rooms
  get 'view_room_history/:id', to: 'rooms#view_room_history', as: "view_room_history"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    get :show_admins
    get :add_admin
  end

  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  delete   '/logout',   to: 'sessions#destroy'

  get     '/login',     to: 'sessions#new'
  get     '/show_admins', to: 'users#show_admins'
  get   '/add_admin',    to: 'users#add_admin'
  # patch   '/add_admin',    to: 'users#add_admin'
  # post     '/add_admin',    to: 'users#add_admin'
  get   '/search_admin',    to: 'users#search_admin'
  patch   '/search_admin',    to: 'users#search_admin'
  post     '/search_admin',    to: 'users#search_admin'
  post     '/make_admin',        to: 'users#make_admin'
  post     '/remove_admin',        to: 'users#remove_admin'
  get      '/admin_manage_room',    to: 'users#admin_manage_room'
  get      '/admin_manage_user',    to: 'users#admin_manage_user'
  get       '/all_user',            to: 'users#all_user'
  post      '/remove_user',         to: 'users#remove_user'

  get       '/search_room',          to: 'bookings#search_room'
  get       '/user_manage_room',      to: 'users#user_manage_room'
  get       '/my_booking_history',            to: 'users#my_booking_history'

  post     '/room_availability_by_date',     to: 'bookings#room_availability_by_date'

  get       '/send_mail',               to: 'bookings#send_mail'
  post      '/dispatch_mail',           to: 'bookings#dispatch_mail'

  post       '/user_booking_history',            to: 'users#user_booking_history'
end

Project1/app/views/layouts/_footer.html.erb
<!--Boilerplate CSS code used from https://www.railstutorial.org/book-->

<footer class="footer">
  <small>
    Developed by Anubhab, Kate, Lei
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   'https://drive.google.com/file/d/0B6myGbDBVWh3TmJObkQteWJsdE0/view?usp=sharing' %></li>
      <li><%= link_to "Contact", 'https://github.ncsu.edu/lzhang45/ECE517_project1' %></li>

    </ul>
  </nav>
</footer>

Project1/app/views/layouts/_header.html.erb
<!--Boilerplate CSS code used from https://www.railstutorial.org/book-->

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Library Booking App", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_logged_in?%>
          <li><%= link_to "Home",   user_path(session[:user_id]) %></li>
        <% end %>
        <li><%= link_to "Help",   'https://drive.google.com/file/d/0B6myGbDBVWh3TmJObkQteWJsdE0/view?usp=sharing' %></li>
        <% if user_logged_in?%>
          <li><%= link_to "Logout", logout_path, method: "delete" %></li>
        <% else %>
            <li><%= link_to "Login", login_path, method: "get" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

Project1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library Booking App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all','data-turbolinks-track'=> 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=>'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div>
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>