Project1/config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  get 'show' => 'bookings#show'
  get 'search_room' =>'bookings#search_room'
  post 'search_room', to: 'bookings#search'
  get 'release_room' =>'bookings#release_room'
  post 'release_room', to: 'bookings#release'
  post 'index',to:'bookings#save_room'
  post'/cancel', to: 'bookings#cancel'

  # get 'sessions/new'
  root  'sessions#new'

  resources :rooms
  get 'view_room_history/:id', to: 'rooms#view_room_history', as: "view_room_history"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    get :show_admins
    get :add_admin
  end

  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  delete   '/logout',   to: 'sessions#destroy'

  get     '/login',     to: 'sessions#new'
  get     '/show_admins', to: 'users#show_admins'
  get   '/add_admin',    to: 'users#add_admin'
  # patch   '/add_admin',    to: 'users#add_admin'
  # post     '/add_admin',    to: 'users#add_admin'
  get   '/search_admin',    to: 'users#search_admin'
  patch   '/search_admin',    to: 'users#search_admin'
  post     '/search_admin',    to: 'users#search_admin'
  post     '/make_admin',        to: 'users#make_admin'
  post     '/remove_admin',        to: 'users#remove_admin'
  get      '/admin_manage_room',    to: 'users#admin_manage_room'
  get      '/admin_manage_user',    to: 'users#admin_manage_user'
  get       '/all_user',            to: 'users#all_user'
  post      '/remove_user',         to: 'users#remove_user'

  get       '/search_room',          to: 'bookings#search_room'
  get       '/user_manage_room',      to: 'users#user_manage_room'
  get       '/my_booking_history',            to: 'users#my_booking_history'

  post     '/room_availability_by_date',     to: 'bookings#room_availability_by_date'

  get       '/send_mail',               to: 'bookings#send_mail'
  post      '/dispatch_mail',           to: 'bookings#dispatch_mail'

  post       '/user_booking_history',            to: 'users#user_booking_history'
end

Project1/app/models/room.rb
class Room < ApplicationRecord
  validates :room_id, presence: true, uniqueness: true
  has_many :booking
end

Project1/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :allowed_user

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
    @user = User.find(session[:user_id])
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    set_room
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  def view_room_history
    @booking=Booking.where("room_id =?", Room.find(params[:id]).room_id)
    @user = User.find(session[:user_id])
    #this means all booking records of this room
    #redirect_to view_room_history_path
  end

  # GET /rooms/1/edit
  def edit
    @room=Room.find(params[:id])
    set_room
    #maybe a bug here
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    # respond_to do |format|
      if @room.save
        # format.html { redirect_to @room, notice: 'Room was successfully created.' }
        # format.json { render :show, status: :created, location: @room }
        flash[:success] = "Room successfully added"
        redirect_to admin_manage_room_path
      else
        # format.html { render :new }
        # format.json { render json: @room.errors, status: :unprocessable_entity }
        flash[:danger] = "Room couldn't be added. Please try again"
        render 'new'
      end
    # end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
      set_room
      if @room.update(room_params)
        flash[:success] = "Room successfully updated"
        redirect_to rooms_path
      else
        flash[:danger] = "Room couldn't be updated. Please try again"
        render 'new'
      end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    set_room
    current_time=Time.new.strftime('%Y-%m-%d %H:%M:%S')
    @record=Booking.where("room_id= ? and starttime > ?",@room.room_id,current_time)
    @record.each do |booking|
    booking.destroy
    end
    @room.destroy

    flash[:success] = "Room successfully removed"
    redirect_to rooms_path

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_id, :building, :size)
    end
end

Project1/app/helpers/rooms_helper.rb
module RoomsHelper
end

Project1/app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_id %>
    <%= f.text_field :room_id %>
  </div>

  <div class="field">
    <%= f.label :building %>
    <%= f.text_field :building %>
  </div>

  <div class="field">
    <%= f.label :size %>
    <%= f.text_field :size %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Project1/app/views/rooms/edit.html.erb
<h1>Edit Room</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@room) do |field| %>
        <%= field.label :room_id %>
        <%= field.text_field :room_id %>

        <%= field.label :building %>
        <%= field.select  :building, ["James B. Hunt", "D. H. Hill"] %>

        <%= field.label :size %>
        <%= field.select  :size, [4, 6, 12] %>


        <%= field.submit "Update room", class: "btn btn-primary" %>
    <% end %>


  </div>
</div>

<%= link_to 'Return to room list', rooms_url %></table>

Project1/app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

  <ul class="list-group">


    <% @rooms.each do |room| %>
        <li class="list-group-item">
          <%= room.room_id %>&nbsp&nbsp&nbsp&nbsp
          <%= room.building %>&nbsp&nbsp&nbsp&nbsp
          <%= link_to 'Details', room %>&nbsp&nbsp&nbsp&nbsp
          <% if @user.Admin%>
            <%= link_to 'Edit', edit_room_path(room) %>&nbsp&nbsp&nbsp&nbsp
            <%= link_to 'Delete', room, method: :delete, data: { confirm: 'Are you sure?' } %>&nbsp&nbsp&nbsp&nbsp
          <%end%>
          <%= link_to 'View_room_history', view_room_history_path(room)%>
      </li>
    <% end %>


  </ul>

<% if @user.Admin%>
    <%= link_to 'Return to manage rooms', admin_manage_room_url %></table>
<%else%>
    <%= link_to 'Return to manage rooms', user_manage_room_url %></table>
<%end%>

Project1/app/views/rooms/new.html.erb
<h1>New Room</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% render 'form', room: @room %>
    <%= form_for(@room) do |field| %>
        <%= field.label :room_id %>
        <%= field.text_field :room_id %>

        <%= field.label :building %>
        <%= field.select  :building, ["James B. Hunt", "D. H. Hill"] %>

        <%= field.label :size %>
        <%= field.select  :size, [4, 6, 12] %>


        <%= field.submit "Add room", class: "btn btn-primary" %>
    <% end %>


  </div>
</div>

<%= link_to 'Return to manage rooms', admin_manage_room_url %>

Project1/app/views/rooms/show.html.erb
<body>
<h2>
  Room <%=@room.room_id%>
</h2>

<ul class="list-group">
  <li class="list-group-item">
    <strong>Building:</strong>
    <%= @room.building %>
  </li>

  <li class="list-group-item">
    <strong>Size:</strong>
    <%= @room.size %>
  </li>



</ul>
</body>


<%= link_to 'Return to room list', rooms_url %></table>

Project1/app/views/rooms/view_room_history.html.erb
<p id="notice"><%= notice %></p>

<h1> Booking history</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="details">
      <thead>
      <tr>
        <th>RoomID</th>
        <% if @user.Admin%>
          <th>Username</th>
          <th>Bookday</th>
        <%end%>
        <th>Date</th>
        <th>Starttime</th>
        <th>Endtime</th>
        <% if @user.Admin%>
          <th> </th>
        <%end%>
        <!--<th colspan="3"></th>-->
      </tr>
      </thead>

      <tbody>
      <% @booking.each do |booking| %>
          <tr>
            <td><%= booking.room_id %></td>
            <% if @user.Admin%>
              <td><%= booking.name %></td>
              <td><%= booking.bookday %></td>
            <%end%>
            <td><%= booking.date.strftime('%Y-%m-%d') %></td>
            <td><%= booking.starttime.strftime('%H:%M:%S') %></td>
            <td><%= booking.endtime.strftime('%H:%M:%S') %></td>
            <% if @user.Admin%>
              <% if Date.parse(booking.date.strftime('%Y-%m-%d'))>=Date.parse(Time.new.strftime('%Y-%m-%d'))%>
                  <td><%= link_to 'cancel', release_room_path(booking), method: :POST, data: { confirm: "Are you sure to cancel it?" }%></td>
              <% end %>
            <%end%>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to 'Return to room list', rooms_url %></table>